api: 2

core: 8.x

projects:
  drupal: 8.6.x
  key_value: 1.x
  key: 1.x
  encrypt: 3.x
  conflict:
    type: module
    download:
      type: git
      branch: 8.x-1.x
      url: "https://github.com/drupaldeploy/drupal-conflict.git"
  multiversion:
    type: module
    download:
      type: git
      branch: 8.x-2.x
      url: "https://github.com/dickolsson/drupal-multiversion.git"
